### ISSUE TITLE
Error on NextJS 14: Element type is invalid

### ISSUE THREAD

**Issue by jolbol1** [typicode/mistcss#10]
I was just trying out usage with a brand new NextJS 14 project, following the steps in the documentation.

When using the Button.mist.css component in a NextJS page I get the following error:
![image](https://github.com/typicode/mistcss/assets/5064896/4ed558ce-01d5-4d74-b353-e2804fe05ece)

Reproduction here:
https://stackblitz.com/edit/nextjs-qhemj9?file=app%2Fpage.tsx

Apologies if I have set something up wrong!

EDIT:
It appears that NextJS gets confused by the import? appending `.tsx` onto the end of it fixes the issue.

Added more example cases to the stackblitz, it seems NextJS is trying to import the css file and therefore the import is undefined when used. Another fix is removing the .css bit from the component

**Comment by typicode** [comment]
Hi,

Thanks for the report and edit. I confirm, I have the same issue.
Working on that :+1:

**Comment by typicode** [comment]
It should be good now :)
Generated file is now `Button.mist.tsx`, it should prevent the issue. Import should be changed to:

```
import { Button } from './Button.mist'
```

**Comment by jolbol1** [comment]
> It should be good now :) Generated file is now `Button.mist.tsx`, it should prevent the issue. Import should be changed to:
> 
> ```
> import { Button } from './Button.mist'
> ```

Sounds good, I think that will stop a lot of confusion as well to be fair!

**Comment by typicode** [comment]
>  that will stop a lot of confusion as well to be fair!

I agree, thanks for the feedback :)
