### ISSUE TITLE
 Request for Additional Usage Examples in Documentation

### ISSUE THREAD

**Issue by yooyea** [typicode/mistcss#12]
Dear Maintainers,

Greetings!

I am a developer from the community who has been working with your project. While the existing documentation provides a solid foundation for understanding and applying the project, I believe that including more usage examples would greatly assist both newcomers and experienced developers in mastering the various features and best practices of the project.

Specifically, I think the following areas could benefit from additional examples:

**Beginner-Level Examples:** Detailed, step-by-step examples for beginners would help them quickly get started with the project.

**Advanced Feature Demonstrations:** Examples that showcase advanced features or complex use cases can help developers understand how to tackle complex problems in real-world scenarios.

**Common Issue Solutions:** Providing examples of common issue solutions can allow developers to quickly find answers when they encounter problems.

**Best Practice Guidelines:** Examples illustrating best practices can help developers avoid common pitfalls and improve the quality and maintainability of their code.

**Integration with Third-Party Services:** If the project is often used for integration with third-party services, examples in this area would be invaluable.

I understand that creating and maintaining documentation requires a significant amount of time and effort, but I believe that adding more examples will enhance the usability of the documentation and the popularity of the project. If needed, I am willing to contribute my part by providing some examples or helping to improve the existing documentation.

Thank you for your contributions to the project and the community!

Best regards,

**Comment by typicode** [comment]
Thank you for the feedback. Do you have examples or cases where you think users may struggle?

**Comment by atmin** [comment]
I'd find "Nested components" example in the "How to" section helpful.

Something along the lines of 

```js
import { List as MistList } from '.components/List.mist';
import { ListItem } from '.components/ListItem.mist';

export function List({ items }: { items: string[] }) {
  return (
    <MistList>
      {items.map((item) => <ListItem>{item}</ListItem>)}
    </MistList>
  );
}
```

**Comment by typicode** [comment]
Docs have been reworked and I hope cover all the different topics. Thanks for the feedback! :)
