### ISSUE TITLE
Nested composibility??

### ISSUE THREAD

**Issue by The-Code-Monkey** [typicode/mistcss#19]
Just throwing the idea of having nested composibility.

E.g. making a button group from a button component that is also made by mist?

**Comment by typicode** [comment]
Good question. For now, I'll keep it simple and see how it goes.

I think that one of the appeal of MistCSS is that you can't do complex things with it. So your components are atomic and simple to understand.

Also UI libs like [shadcn/ui](https://ui.shadcn.com/docs/components/breadcrumb) exports multiple components that you compose later.

It's possible to do the same with MistCSS though I didn't have the time to document it yet:
https://github.com/typicode/mistcss/releases/tag/v0.3.4

I may revisit this idea though.

**Comment by The-Code-Monkey** [comment]
Awesome yeah, I'm not the biggest fan on shadcn and was wanting to build something a little more my style/control. I understand it's early days and getting single components working nicely is the priority.

**Comment by typicode** [comment]
Closing since v1 works differently now.
