### ISSUE TITLE
className not apply

### ISSUE THREAD

**Issue by Inaztm** [typicode/mistcss#27]
Generates {... props} before className.

<img width="592" alt="image" src="https://github.com/typicode/mistcss/assets/9611099/4a8d9fa6-a736-494d-86af-ca1430c5d79c">

Can use the cva solution or just add other classes after the "scoped" class?

**Comment by typicode** [comment]
Hi,

I'm not familiar with CVA, but can you try:

```tsx
// CustomBlock.tsx
import { Block } from './Block.mist'

export function CustomBlock({ children, ...props }) {
  return <Block className="Block" { ...props }>children</Block>
}
```

**Comment by Inaztm** [comment]
@typicode 

Doesn't work.
<img width="406" alt="image" src="https://github.com/typicode/mistcss/assets/9611099/3910b8f8-46dd-4d45-87e6-7ce69ff56905">
<img width="361" alt="image" src="https://github.com/typicode/mistcss/assets/9611099/9ebe95d1-b852-4710-ba00-6e9c63765692">

In this example, className is ignored

**Comment by The-Code-Monkey** [comment]
This is related to the ticket I added

**Comment by sergupe** [comment]
I think It is the problem mentioned by @The-Code-Monkey indeed. The code is done so the className are PascalCase and not Camel or Kebab case.

@Inaztm could you try with a PascalCase className?

**Comment by The-Code-Monkey** [comment]
I will be fixing this tomorrow so the classname is passed through the same as people define it, but the component name will be Pascal case still
