### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by The-Code-Monkey** [typicode/mistcss#32]
@typicode what are your thoughts on sass support I was looking to add it would this be ok?

**Comment by The-Code-Monkey** [comment]
There are two ways we could support sass one we keep the sass file and import that into the built component,

Or we could convert the sass to CSS and then import that. But that would mean keeping a sass and a CSS file in the directory

**Comment by typicode** [comment]
Hi @The-Code-Monkey,

I'm kind of satisfied with the way MistCSS works currently so I'd rather not change code too much and gather feedback first before adding more features. I have some ideas as well but I need a bit time to play with them.

Also I plan to work on the documentation a bit more.

For Sass, I'd go with the second option and do it the Remix way:
https://remix.run/docs/en/main/styling/postcss#css-preprocessors

So adding a section to how to and have sass convert from `.mist.scss` to `.mist.css` then mistcss would pick from there would be the simplest option without changing how MistCSS currently works.
