### ISSUE TITLE
Generated components' name end with mist.css.tsx

### ISSUE THREAD

**Issue by gyutato** [typicode/mistcss#33]
## AS-IS
- I followed exactly what [the tutorial from the document](https://typicode.github.io/mistcss/getting-started.html#usage) says.
- I compiled the mistCSS filed using the command below:
```json
"mist": "mistcss ./src",
```
- However the file name of components generated ends with `mist.css.tsx`.
  - e.g. from `src/components/Button.mist.css` to `src/components/Button.mist.css.tsx`
 
## TO-BE
- The file name should end with `mist.tsx` following the document.

**Comment by gyutato** [comment]
My mistake that I didn't check the closed PR #23. I updated to the latest version 0.3.7; problem solved.

**Comment by The-Code-Monkey** [comment]
@gyutato glad to hear it, feel free to open more issues in the future if you find anything.
