### ISSUE TITLE
[Question] Will there be support for other Javascript Frameworks, like VueJs?

### ISSUE THREAD

**Issue by ThaDaVos** [typicode/mistcss#35]
Just curious, as the IDEA is great, but will there be support for other Javascript Frameworks thenn ReactJs? Maybe VueJs for example?

**Comment by typicode** [comment]
Yes, there will be.

**Comment by ThaDaVos** [comment]
Checking the code, only a `Renderer` seems to be needed

**Comment by typicode** [comment]
Exactly! I'm not 100% decided on the renderer term. If you have suggestions.

**Comment by ThaDaVos** [comment]
I have a few:
- `Renderer` - as it renders it into the format of the Javascript Framework
- `Transpiler` - as it converts and transpiles it into the format of the Javascript Framework
- `Builder` - It builds the component in the Javascript Framework, you could even try and implement the Builder pattern for it, [see](https://www.dofactory.com/javascript/design-patterns/builder)
- `Templater` - As it sets up the template for the Javascript Framework to compile from

Just an idea - maybe it shouldn't be a single thing but be composed of multiple, each with their own corresponding job - then you could have a `composer` with takes care of all this separate components and builds up the template  - as each Javascript Framework has their own structure - having a overal `composer` with sub-modules maybe allows easier implementation

**Comment by ThaDaVos** [comment]
Also, as I used to work with Vue - maybe I can help and try to setup the Vue counterpart (when i have time) and see what implementation would benefit the most

**Comment by The-Code-Monkey** [comment]
I prefer the word transpiler

**Comment by The-Code-Monkey** [comment]
@ThaDaVos if you could reply with what a simple button component would look like in vue and typescript, then i could add it from that.

**Comment by ThaDaVos** [comment]
I would prefer the word `Composer` - which may use a `Transpiler` or `Builder` to set it up

An example would be:
https://play.vuejs.org/#eNp9kbFOwzAQhl/l5AVQqwQEU5VWFNQBBkDQ0UuaXFu3jm3Z51IpyrtjO21gQN3s+7+zv9O1bG5MdvDIJqxwlRWGwCF5M+NKNEZbghYsrqGDtdUNXAX0iiuuKq0cQaW9IrQwjcz17Q1XRd6/EvrDhbAxsiSMNypWnkgreKykqPZTzk7doxFns3ldw12R90iPm9lyi3BqKlf6gLAtHawQFaQnsIa2HRy6Dkg06LIij/ZFPnzOxoxcEF6LTbZzWoVZW64AokFjhET7bkiEgTibQEpiVkqpv19TjazH8blebbHa/1PfuWOscfZh0aE9IGdDRqXdIPXx4usNj+E8hI2uvQz0hfATnZY+OvbYk1d10P7DJduXtDGhNku3OBIqdx4qikaySzxnYYvPF0b/1b3PHlIfVx3rfgCVPbtM

**Comment by ThaDaVos** [comment]
There are even nicer ways of writing the component - which is without the `template` tag - but I think this is the most easy to understand

**Comment by ThaDaVos** [comment]
This one is without typescript definitions - but it auto infers data typings

**Comment by ThaDaVos** [comment]
I just took the example from the docs - if you want a more elaborate example, I need to cook something up for you

You could take a look at how Vuetify does it:
https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VBtn/VBtn.tsx

**Comment by typicode** [comment]
Vue support added in `v0.5.2` :+1:
