### ISSUE TITLE
The GitHub page's buttons are redirecting to 404 not found

### ISSUE THREAD

**Issue by HaecheonLee** [typicode/mistcss#43]
Hello,

In the [GitHub page](https://typicode.github.io/mistcss/), there are two buttons: **Get Started** and **Docs** on the bottom. They are leading to https://typicode.github.io/mistcss/mistcss/intro and https://typicode.github.io/intro and it looks like not set up properly. It contains `mistcss` twice in the url, and the other one doesn't contain.

**Comment by typicode** [comment]
Thanks for the heads up! Should be good. Let me know if you find other issues, I just published the new docs.

**Comment by HaecheonLee** [comment]
Looks good! I am closing the issue.
