### ISSUE TITLE
[Question] There is no way get autocompletion?

### ISSUE THREAD

**Issue by scythewyvern** [typicode/mistcss#44]
when i hit `control + space` i can't see any css rule, only pseudo things
am i doing something wrong or it is expected?

i use latest mistcss v0.4.0

```css
@scope (button.my-button) {
  :scope {
   /* ...rules */    
  }
}

```

**Comment by The-Code-Monkey** [comment]
That would be an editor issue not an issue with the library

**Comment by scythewyvern** [comment]
> That would be an editor issue not an issue with the library

yes, i understand, just want to know maybe here is some workaround

**Comment by typicode** [comment]
I tried in VSCode and experiencing the same. It seems like `@scope` is not yet recognized making completion not as good as when you write CSS outside of it.

I suppose completion will improve automatically in the future.
