### ISSUE TITLE
[Bug] The link is not working properly when clicked Docs in the documentation page

### ISSUE THREAD

**Issue by HaecheonLee** [typicode/mistcss#49]
This looks regression of the issue which was closed a week ago. The link of Docs redirects to [https://typicode.github.io/intro](https://typicode.github.io/intro) instead of [https://typicode.github.io/mistcss/intro](https://typicode.github.io/mistcss/intro)

You can check **Read docs** in the [documentation page](https://typicode.github.io/mistcss/)

**Comment by typicode** [comment]
Fixed! Thank you!
