### ISSUE TITLE
`--at-apply` gets exposed as Props.

### ISSUE THREAD

**Issue by totto2727** [typicode/mistcss#59]
Tailwind` and `UnoCSS` can use the `--at-apply` format instead of `@apply`.
Lightning CSS cannot use `@apply` by default, so you need to use this one.

https://github.com/unocss/unocss/issues/2910

```css
@scope (a.base-anchor) {
  :scope {
    --at-apply: "text-blue-500 underline";
  }
}
```

However, it seems to be exposed as Props because it matches the syntax of CSS Variables.

```tsx
---
// Generated by MistCSS, do not modify
import type { HTMLAttributes } from 'astro/types'
import './Anchor.mist.css'

type Props = { atApply?: string } & HTMLAttributes<'a'>

const { atApply, ...props } = Astro.props
---

<a {...props} style={{ '--at-apply': atApply }} class=“base-anchor” ><slot /></a>
```

Probably no harm is done since it is a type issue, but I wanted to prevent unnecessary type exposures if possible.
Is it acceptable for PRs to add a process to ignore certain variable names?
(For the time being, I plan to hard-code the variable names without adding Option)

```js
// UnoCSS Default.
['--at-apply', '--uno-apply', '--uno']
```

https://github.com/typicode/mistcss/blob/6747d0cd486128a511a19f46041e56be9a8bc8cd/src/parser.ts#L54-L59

**Comment by typicode** [comment]
`--at-apply` is ignored now. Thanks for the heads up!
