### ISSUE TITLE
Open External Links in a New Tab + Update Social Media Icon

### ISSUE THREAD

**Issue by PrateekSingh43** [typicode/mistcss#61]
I noticed that the header's GitHub and Twitter (now X) icons don’t open links in a new tab. Clicking these links currently redirects the user away from the MistCSS docs page, interrupting the user experience. I suggest updating them to open in a new tab for smoother navigation.

Additionally, the Twitter icon still displays the old bird logo, which is outdated since Twitter has rebranded to X. Updating the icon would keep the site modern and consistent. 

Proposed Changes:

Set external links (GitHub and X) to open in a new tab.
Replace the Twitter bird icon with the X logo. 

If this sounds good, please assign this issue to me, and I can go ahead and make the necessary changes. Thanks!

**Comment by typicode** [comment]
Thanks for the feedback! I usually prefer links to not open tabs by default.

**Comment by PrateekSingh43** [comment]
I created this issue because, in your other project, Husky, the icon for Twitter is labeled as 'X.' Additionally, the icons for GitHub and 'X' both open in a new tab, so I thought this might be overlooked by the developers

**Comment by typicode** [comment]
Yes, you're totally right about this, good catch. I used a different doc template for this project and didn't pay much attention to this.
