### ISSUE TITLE
Example repo/folder with post-css CLI

### ISSUE THREAD

**Issue by bcomnes** [typicode/mistcss#68]
Do you have an example repo or folder with a tooling setup example using postcss cli, tsc and mistcss?

**Comment by typicode** [comment]
Not really.

For quick local testing, I'm just using default Next.js install:

```
npx create-next-app@latest
npm i mistcss -D
```

Then you just have to add `mistcss: {},` in `postcss.config.js` and import `mist.css` in the layout.

**Comment by ultrox** [comment]
@typicode I'm not using nextjs but vite with react plugin. Do you have working example?

Here is my attempt to recreate minimal working example following your doc's.

https://stackblitz.com/edit/vitejs-vite-x3yyqw?file=README.md,postcss.config.js,src%2Flayout.tsx,src%2Fmist.css,package.json

**Comment by typicode** [comment]
I don't but thanks for the link. Actually `Layout.tsx` isn't used/imported, try `import './mist.css` from `App.tsx` instead.

**Comment by ultrox** [comment]
It started to work for some reason even before i connected the layout in app. It works now. Thanks
