### ISSUE TITLE
Implement goto definiiton

### ISSUE THREAD

**Issue by wesbos** [typicode/mistcss#73]
This might be out of the scope of this project, but one thing I miss is bring able to click through from the Component to the CSS definition. 

I have this setup with CSS modules and the `typescript-plugin-css-modules` plugin, but since this isn't a runtime thing, I'm not sure it's even possible with TypeScript. Maybe via a sourcemap?

Right now I can get around it with the `%` operator in VS Cede.

<img width="982" alt="Screenshot 2024-12-09 at 10 04 57 AM" src="https://github.com/user-attachments/assets/cd20b012-b8b3-447a-8587-69d71331ee7d">

**Comment by typicode** [comment]
I'd love to explore this idea (and others for MistCSS), main issue currently is lack of OSS funding and time.
So maybe in the future.
